server:
  port: 8080

spring:
  application:
    name: monster company backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:monster_company}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:12345}
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    properties:
      hibernate:
        show_sql: true
        format_sql: false
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yml

jwt:
  secret: spring
  expiration: 3600000
#logging:
#  level:
#    org:
#      hibernate:
#        sql: debug
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
