server:
  port: 8080

spring:
  application:
    name: monster company backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://monster_pg:5432/monster_company
    username: postgres
    password: 12345
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
jwt:
  secret: spring
  expiration: 3600000
#logging:
#  level:
#    org:
#      hibernate:
#        sql: debug
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
