version: "3.7"

services:
  postgres:
    image: postgres:14
    container_name: monster_pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: monster_company
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - ./postgres/db:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  app:
    build:
      context: ..
    container_name: monster-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres